proxy:
  hostname: '' #127.0.0.1
  port: '' #7890
  scheme: '' #http # 支持“socks4”、“socks5”和“http”，不填则不使用代理
user:
  admin: null
  api_hash: 63a159baff51
  api_id: 123456789
  bot_token: 6108379846:AAH2-gYW7YE
