version: '3'
services:
  bot:
    build: .
    container_name: sticker-finder
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./data:/app/data
    restart: on-failure:2
